project:
  type: website

website:
  title: "Los Angeles Education"
  navbar:
    left:
      - href: index.qmd
        text: California
      - href: washington_edu.qmd
        text: Washington
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



